import { requireAnyRole } from '@/lib/auth'; import { redirect } from 'next/navigation'; import { query } from '@/lib/db'; import TeamReviewForm from '@/components/rubric/TeamReviewForm';import Link from 'next/link';
export default async function Evaluate({params}:{params:Promise<{reviewId:string;teamId:string}>}){
 const u=await requireAnyRole(['FACULTY']); if(!u?.facultyId) redirect('/login'); const {reviewId,teamId}=await params; const rid=Number(reviewId),tid=Number(teamId);
 const ctx=(await query<any>(`SELECT p.title,t.team_code,t.team_name,rv.name review_name,rv.maximum_marks,rv.review_date,f.name guide_name,f.designation,f.department,ev.id evaluation_id,COALESCE(ev.status,'DRAFT') evaluation_status,ev.return_scope,ev.faculty_remarks,(SELECT COUNT(*) FROM review_file_requirements_v4 rfr WHERE rfr.review_id=rv.id) requirement_count,COALESCE(sub.status,'NOT_SUBMITTED') submission_status FROM project_allocations_v2 pa JOIN projects_v2 p ON p.id=pa.project_id JOIN teams_v2 t ON t.id=pa.team_id JOIN pbl_reviews_v2 rv ON rv.pbl_cycle_id=p.pbl_cycle_id JOIN faculty_v2 f ON f.id=pa.guide_faculty_id LEFT JOIN review_evaluations_v3 ev ON ev.review_id=rv.id AND ev.team_id=t.id LEFT JOIN team_review_submissions_v4 sub ON sub.review_id=rv.id AND sub.team_id=t.id WHERE pa.guide_faculty_id=$1 AND pa.team_id=$2 AND rv.id=$3 AND rv.status='PUBLISHED' AND pa.status='ACTIVE'`,[u.facultyId,tid,rid]))[0];
 if(!ctx) redirect('/faculty/reviews');const locked=Number(ctx.requirement_count)>0&&ctx.submission_status!=='SUBMITTED';
 if(locked)return <section className="section"><div className="container"><h1>{ctx.review_name}: {ctx.team_code}</h1><div className="notice error"><b>Evaluation locked.</b> This review requires a completed team submission before marks can be entered.</div><Link className="btn secondary" href={`/faculty/reviews/${rid}/team/${tid}/files`}>Review Submission Status</Link></div></section>;
 const students=await query<any>(`SELECT e.id enrollment_id,s.usn,s.name,COALESCE(sc.contribution_percent,100) contribution_percent,COALESCE(sc.correction_status,'OK') correction_status,sc.hod_comment FROM team_members_v2 tm JOIN student_enrollments_v2 e ON e.id=tm.enrollment_id JOIN students_v2 s ON s.id=e.student_id LEFT JOIN student_contributions_v3 sc ON sc.evaluation_id=$2 AND sc.enrollment_id=e.id WHERE tm.team_id=$1 AND tm.status='ACTIVE' ORDER BY s.usn`,[tid,ctx.evaluation_id||0]);
 const items=await query<any>(`SELECT ri.id,ri.co_code,ri.criterion_name,ri.max_marks,ri.display_order,COALESCE(jsonb_agg(jsonb_build_object('id',rl.id,'label',rl.level_label,'marks',rl.marks,'descriptor',rl.descriptor,'order',rl.display_order) ORDER BY rl.display_order) FILTER(WHERE rl.id IS NOT NULL),'[]'::jsonb) levels FROM rubrics_v2 r JOIN rubric_items_v2 ri ON ri.rubric_id=r.id LEFT JOIN rubric_levels_v2 rl ON rl.rubric_item_id=ri.id WHERE r.review_id=$1 GROUP BY ri.id ORDER BY ri.display_order`,[rid]);
 const scoreRows=ctx.evaluation_id?await query<any>(`SELECT rubric_item_id,selected_level_id FROM team_rubric_scores_v3 WHERE evaluation_id=$1`,[ctx.evaluation_id]):[]; const initialScores=Object.fromEntries(scoreRows.map((x:any)=>[String(x.rubric_item_id),Number(x.selected_level_id)]));
 return <section className="section"><div className="container"><h1>{ctx.review_name}: {ctx.team_code}</h1><div className="card"><p><b>Team:</b> {ctx.team_name}</p><p><b>Project:</b> {ctx.title}</p><p><b>Guide:</b> {ctx.guide_name} · {ctx.designation||''} · {ctx.department||''}</p><p><b>Submission:</b> {Number(ctx.requirement_count)>0?'Submitted':'No files required'}</p><p><b>Status:</b> {ctx.evaluation_status}</p>{Number(ctx.requirement_count)>0&&<Link className="btn secondary" href={`/faculty/reviews/${rid}/team/${tid}/files`}>Review Files</Link>}</div><TeamReviewForm reviewId={rid} teamId={tid} items={items} students={students} initialScores={initialScores} status={ctx.evaluation_status} returnScope={ctx.return_scope} facultyRemarks={ctx.faculty_remarks}/></div></section>
}
