import {NextResponse} from 'next/server'; import {requireAnyRole} from '@/lib/auth'; import {pool} from '@/lib/db';
export async function POST(req:Request,{params}:{params:Promise<{reviewId:string;teamId:string}>}){
 const u=await requireAnyRole(['FACULTY']); if(!u?.facultyId)return NextResponse.redirect(new URL('/login',req.url),303); const {reviewId,teamId}=await params; const rid=Number(reviewId),tid=Number(teamId); const form=await req.formData(); const action=String(form.get('action')||'SAVE_DRAFT'); const c=await pool.connect();
 try{await c.query('BEGIN');
  const gate=(await c.query(`SELECT rv.id,(SELECT COUNT(*) FROM review_file_requirements_v4 rfr WHERE rfr.review_id=rv.id)::int requirement_count,COALESCE(sub.status,'NOT_SUBMITTED') submission_status FROM project_allocations_v2 pa JOIN projects_v2 p ON p.id=pa.project_id JOIN pbl_reviews_v2 rv ON rv.pbl_cycle_id=p.pbl_cycle_id LEFT JOIN team_review_submissions_v4 sub ON sub.review_id=rv.id AND sub.team_id=pa.team_id WHERE pa.guide_faculty_id=$1 AND pa.team_id=$2 AND rv.id=$3 AND rv.status='PUBLISHED' AND pa.status='ACTIVE'`,[u.facultyId,tid,rid])).rows[0]; if(!gate)throw new Error('Not authorised'); if(Number(gate.requirement_count)>0&&gate.submission_status!=='SUBMITTED')throw new Error('Team review submission is incomplete. Evaluation is locked.');
  let ev=(await c.query(`SELECT * FROM review_evaluations_v3 WHERE review_id=$1 AND team_id=$2 FOR UPDATE`,[rid,tid])).rows[0];
  if(ev && !['DRAFT','RETURNED_FOR_CORRECTION'].includes(ev.status)) throw new Error('Review is locked while awaiting or after HoD verification');
  if(!ev) ev=(await c.query(`INSERT INTO review_evaluations_v3(review_id,team_id,guide_faculty_id) VALUES($1,$2,$3) RETURNING *`,[rid,tid,u.facultyId])).rows[0];
  const entire=ev.status==='DRAFT'||ev.return_scope==='ENTIRE';
  const items=(await c.query(`SELECT ri.id FROM rubrics_v2 r JOIN rubric_items_v2 ri ON ri.rubric_id=r.id WHERE r.review_id=$1 ORDER BY ri.display_order`,[rid])).rows;
  if(entire){for(const it of items){const lid=Number(form.get(`selected_${it.id}`)); if(!lid&&action==='SUBMIT')throw new Error('Complete all team rubric criteria before submission'); if(lid){const lev=(await c.query(`SELECT id,marks FROM rubric_levels_v2 WHERE id=$1 AND rubric_item_id=$2`,[lid,it.id])).rows[0]; if(!lev)throw new Error('Invalid rubric selection'); await c.query(`INSERT INTO team_rubric_scores_v3(evaluation_id,rubric_item_id,selected_level_id,marks_awarded) VALUES($1,$2,$3,$4) ON CONFLICT(evaluation_id,rubric_item_id) DO UPDATE SET selected_level_id=EXCLUDED.selected_level_id,marks_awarded=EXCLUDED.marks_awarded`,[ev.id,it.id,lid,lev.marks]);}}}
  const students=(await c.query(`SELECT tm.enrollment_id,COALESCE(sc.correction_status,'OK') correction_status FROM team_members_v2 tm LEFT JOIN student_contributions_v3 sc ON sc.evaluation_id=$2 AND sc.enrollment_id=tm.enrollment_id WHERE tm.team_id=$1 AND tm.status='ACTIVE'`,[tid,ev.id])).rows;
  for(const s of students){const editable=ev.status==='DRAFT'||ev.return_scope==='ENTIRE'||s.correction_status==='RETURNED'; if(!editable)continue; const pct=Number(form.get(`contribution_${s.enrollment_id}`)); if(!Number.isFinite(pct)||pct<0||pct>100)throw new Error('Contribution indicator must be between 0 and 100'); await c.query(`INSERT INTO student_contributions_v3(evaluation_id,enrollment_id,contribution_percent,correction_status,hod_comment) VALUES($1,$2,$3,'OK',NULL) ON CONFLICT(evaluation_id,enrollment_id) DO UPDATE SET contribution_percent=EXCLUDED.contribution_percent,correction_status='OK',hod_comment=NULL,updated_at=NOW()`,[ev.id,s.enrollment_id,pct]);}
  const remarks=String(form.get('facultyRemarks')||'').trim(); const declaration=form.get('declaration')==='1'; if(action==='SUBMIT'&&!declaration)throw new Error('Faculty declaration must be accepted before submission');
  const next=action==='SUBMIT'?'PENDING_HOD_VERIFICATION':'DRAFT'; await c.query(`UPDATE review_evaluations_v3 SET status=$1,faculty_remarks=$2,faculty_declaration_accepted=$3,submitted_at=CASE WHEN $1='PENDING_HOD_VERIFICATION' THEN NOW() ELSE submitted_at END,return_scope=NULL,hod_user_id=CASE WHEN $1='PENDING_HOD_VERIFICATION' THEN NULL ELSE hod_user_id END,hod_comments=CASE WHEN $1='PENDING_HOD_VERIFICATION' THEN NULL ELSE hod_comments END,updated_at=NOW() WHERE id=$4`,[next,remarks,declaration,ev.id]);
  if(action==='SUBMIT'){const hods=(await c.query(`SELECT DISTINCT u.id FROM users_v2 u JOIN user_roles_v2 ur ON ur.user_id=u.id JOIN roles_v2 r ON r.id=ur.role_id WHERE r.code='HOD' AND u.is_active`)).rows; for(const h of hods) await c.query(`INSERT INTO notifications_v3(user_id,title,message,link) VALUES($1,'PBL review awaiting verification',$2,$3)`,[h.id,`Review ${rid} for team ${tid} was submitted by ${u.displayName}.`,`/hod/review-verification/${ev.id}`]);}
  await c.query('COMMIT'); return NextResponse.redirect(new URL('/faculty/reviews',req.url),303);
 }catch(e){await c.query('ROLLBACK');return new NextResponse(e instanceof Error?e.message:'Review save failed',{status:400})}finally{c.release()}
}
