import {requireAnyRole} from '@/lib/auth';import {redirect,notFound} from 'next/navigation';import {query} from '@/lib/db';
export default async function Verify({params}:{params:Promise<{evaluationId:string}>}){const u=await requireAnyRole(['HOD']);if(!u)redirect('/login');const {evaluationId}=await params;const eid=Number(evaluationId);
 const ctx=(await query<any>(`SELECT ev.*,rv.name review_name,rv.maximum_marks,t.team_code,t.team_name,p.title project_title,p.problem_statement,p.domain,f.name guide_name,f.designation,f.department FROM review_evaluations_v3 ev JOIN pbl_reviews_v2 rv ON rv.id=ev.review_id JOIN teams_v2 t ON t.id=ev.team_id LEFT JOIN project_allocations_v2 pa ON pa.team_id=t.id AND pa.status='ACTIVE' LEFT JOIN projects_v2 p ON p.id=pa.project_id LEFT JOIN faculty_v2 f ON f.id=ev.guide_faculty_id WHERE ev.id=$1`,[eid]))[0];if(!ctx)notFound();
 const scores=await query<any>(`SELECT ri.id rubric_item_id,ri.co_code,ri.criterion_name,ri.max_marks,trs.marks_awarded,rl.level_label,rl.descriptor FROM team_rubric_scores_v3 trs JOIN rubric_items_v2 ri ON ri.id=trs.rubric_item_id JOIN rubric_levels_v2 rl ON rl.id=trs.selected_level_id WHERE trs.evaluation_id=$1 ORDER BY ri.display_order`,[eid]);
 const students=await query<any>(`SELECT sc.enrollment_id,s.name,s.usn,sc.contribution_percent,sc.correction_status,sc.hod_comment FROM student_contributions_v3 sc JOIN student_enrollments_v2 e ON e.id=sc.enrollment_id JOIN students_v2 s ON s.id=e.student_id WHERE sc.evaluation_id=$1 ORDER BY s.usn`,[eid]);
 const coMarks:Record<string,number>={},coMax:Record<string,number>={};for(const x of scores){coMarks[x.co_code]=(coMarks[x.co_code]||0)+Number(x.marks_awarded);coMax[x.co_code]=(coMax[x.co_code]||0)+Number(x.max_marks)}const teamTotal=Object.values(coMarks).reduce((a,b)=>a+b,0),totalMax=Object.values(coMax).reduce((a,b)=>a+b,0);const actionable=ctx.status==='PENDING_HOD_VERIFICATION';
 return <section className="section"><div className="container"><h1>HoD Review Verification</h1><div className="card"><h2>{ctx.review_name} — {ctx.team_code}</h2><p><b>Team:</b> {ctx.team_name}</p><p><b>Project:</b> {ctx.project_title||'—'}</p><p><b>Guide:</b> {ctx.guide_name} · {ctx.designation||''} · {ctx.department||''}</p><p><b>Status:</b> {ctx.status}</p><p><b>Faculty remarks:</b> {ctx.faculty_remarks||'—'}</p></div>
 <h2>Team Rubric Evaluation</h2>{scores.map((s:any)=><div className="card" key={s.rubric_item_id}><h3>{s.co_code} — {s.criterion_name}</h3><p><b>{s.level_label}: {s.marks_awarded} / {s.max_marks}</b></p><p>{s.descriptor}</p></div>)}
 <div className="card"><h3>Team Result</h3>{Object.entries(coMarks).map(([co,m])=><p key={co}><b>{co}:</b> {m.toFixed(2)} / {(coMax[co]||0).toFixed(2)}</p>)}<p><b>Total:</b> {teamTotal.toFixed(2)} / {totalMax.toFixed(2)}</p></div>
 <h2>Student Contributions & Derived Marks</h2><form action={`/api/hod/review-verification/${eid}`} method="post"><div className="tablewrap"><table><thead><tr><th>Return?</th><th>Student</th><th>USN</th><th>Contribution</th>{Object.keys(coMarks).map(co=><th key={co}>{co}</th>)}<th>Total</th></tr></thead><tbody>{students.map((s:any)=>{const pct=Number(s.contribution_percent);return <tr key={s.enrollment_id}><td>{actionable?<input type="checkbox" name="selectedStudents" value={s.enrollment_id}/>:s.correction_status}</td><td>{s.name}</td><td>{s.usn}</td><td>{pct}%</td>{Object.entries(coMarks).map(([co,m])=><td key={co}>{(m*pct/100).toFixed(2)} / {coMax[co].toFixed(2)}</td>)}<td><b>{(teamTotal*pct/100).toFixed(2)}</b> / {totalMax.toFixed(2)}</td></tr>})}</tbody></table></div>
 {actionable&&<><div className="field"><label>HoD comments / reason for return</label><textarea name="comments"/></div><button className="btn" name="action" value="APPROVE">Approve Entire Review</button> <button className="btn danger" name="action" value="RETURN_ENTIRE_REVIEW">Return Entire Review</button> <button className="btn secondary" name="action" value="RETURN_STUDENTS">Return Selected Student(s)</button></>}
 </form>{!actionable&&ctx.hod_comments&&<div className="notice"><b>HoD comments:</b> {ctx.hod_comments}</div>}</div></section>}
