import { requireAnyRole } from '@/lib/auth';
import { query } from '@/lib/db';
import { redirect,notFound } from 'next/navigation';

export default async function StudentReview({params}:{params:Promise<{reviewId:string}>}){
  const u=await requireAnyRole(['STUDENT']); if(!u?.studentId) redirect('/login'); const {reviewId}=await params;
  const ctx=(await query<any>(`SELECT rv.id review_id,rv.name,rv.maximum_marks,t.id team_id,t.team_code,t.team_name,p.title project_title,ev.id evaluation_id,ev.status evaluation_status FROM pbl_reviews_v2 rv JOIN teams_v2 t ON t.pbl_cycle_id=rv.pbl_cycle_id JOIN team_members_v2 tm ON tm.team_id=t.id AND tm.status='ACTIVE' JOIN student_enrollments_v2 e ON e.id=tm.enrollment_id LEFT JOIN project_allocations_v2 pa ON pa.team_id=t.id AND pa.status='ACTIVE' LEFT JOIN projects_v2 p ON p.id=pa.project_id LEFT JOIN review_evaluations_v3 ev ON ev.review_id=rv.id AND ev.team_id=t.id WHERE rv.id=$1 AND e.student_id=$2 AND rv.status='PUBLISHED' LIMIT 1`,[Number(reviewId),u.studentId]))[0];
  if(!ctx) notFound();
  const items=await query<any>(`SELECT ri.id,ri.co_code,ri.criterion_name,ri.max_marks,COALESCE(jsonb_agg(jsonb_build_object('id',rl.id,'label',rl.level_label,'marks',rl.marks,'descriptor',rl.descriptor,'order',rl.display_order) ORDER BY rl.display_order) FILTER(WHERE rl.id IS NOT NULL),'[]'::jsonb) levels,trs.selected_level_id,trs.marks_awarded FROM rubrics_v2 r JOIN rubric_items_v2 ri ON ri.rubric_id=r.id LEFT JOIN rubric_levels_v2 rl ON rl.rubric_item_id=ri.id LEFT JOIN team_rubric_scores_v3 trs ON trs.evaluation_id=$2 AND trs.rubric_item_id=ri.id WHERE r.review_id=$1 GROUP BY ri.id,trs.selected_level_id,trs.marks_awarded ORDER BY ri.display_order`,[Number(reviewId),ctx.evaluation_id||0]);
  const showEvaluation=ctx.evaluation_id && ['SUBMITTED','PENDING_HOD_VERIFICATION','RETURNED_FOR_CORRECTION','VERIFIED'].includes(ctx.evaluation_status);
  const contributions=showEvaluation?await query<any>(`SELECT s.name,s.usn,sc.contribution_percent FROM student_contributions_v3 sc JOIN student_enrollments_v2 e ON e.id=sc.enrollment_id JOIN students_v2 s ON s.id=e.student_id WHERE sc.evaluation_id=$1 ORDER BY s.usn`,[ctx.evaluation_id]):[];
  return <section className="section"><div className="container"><h1>{ctx.name}</h1><p><b>{ctx.team_code} — {ctx.team_name}</b>{ctx.project_title?<> · {ctx.project_title}</>:null}</p><p className="lead">{showEvaluation?`Team evaluation status: ${ctx.evaluation_status}`:'Published rubric — evaluation has not yet been submitted.'}</p>
    {items.map((it:any)=><div className="card" key={it.id}><h3>{it.co_code} — {it.criterion_name} <small>({it.max_marks} marks)</small></h3>{it.levels.map((l:any)=><div className="rubric-choice" key={l.id}><b>{l.label} — {l.marks}</b>: {l.descriptor}{showEvaluation&&Number(it.selected_level_id)===Number(l.id)&&<strong> ✓ Selected</strong>}</div>)}{showEvaluation&&<p><b>Team marks:</b> {it.marks_awarded} / {it.max_marks}</p>}</div>)}
    {showEvaluation&&<><h2>Team Contribution Indicators</h2><p className="muted">Visible to all members of this team.</p><div className="tablewrap"><table><thead><tr><th>Student</th><th>USN</th><th>Contribution Indicator</th></tr></thead><tbody>{contributions.map((c:any)=><tr key={c.usn}><td>{c.name}</td><td>{c.usn}</td><td>{c.contribution_percent}%</td></tr>)}</tbody></table></div>{ctx.evaluation_status==='VERIFIED'?<div className="card"><h2>Official Verified Rubric Sheet</h2><p>Download the print-ready two-page PDF for student, Project Guide and HoD physical signatures.</p><a className="btn" href={`/student/reviews/${reviewId}/rubric-sheet`}>Download Rubric Sheet (PDF)</a></div>:<div className="notice">Download Rubric Sheet: Disabled — Status: Pending Verification</div>}</>}
  </div></section>
}
