import {NextResponse} from 'next/server';import {requireAnyRole} from '@/lib/auth';import {pool,query} from '@/lib/db';import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
export const runtime='nodejs';
const A4:[number,number]=[595.28,841.89];
function clean(s:any){return String(s??'').replace(/[\u2013\u2014]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[^\x20-\x7E]/g,' ')}
function wrap(text:string,max:number,font:any,size:number){const words=clean(text).split(/\s+/);const out:string[]=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(font.widthOfTextAtSize(test,size)<=max)line=test;else{if(line)out.push(line);line=w}}if(line)out.push(line);return out.length?out:[''];}
function drawText(page:any,text:any,x:number,y:number,font:any,size=8,maxWidth?:number,lineHeight=10){const lines=maxWidth?wrap(clean(text),maxWidth,font,size):[clean(text)];lines.forEach((l,i)=>page.drawText(l,{x,y:y-i*lineHeight,size,font,color:rgb(.08,.12,.17)}));return y-lines.length*lineHeight}
function center(page:any,text:any,y:number,font:any,size=10){const t=clean(text),w=font.widthOfTextAtSize(t,size);page.drawText(t,{x:(A4[0]-w)/2,y,size,font,color:rgb(.05,.12,.22)})}
function line(page:any,x1:number,y1:number,x2:number,y2:number,width=.6){page.drawLine({start:{x:x1,y:y1},end:{x:x2,y:y2},thickness:width,color:rgb(.2,.25,.3)})}
function cell(page:any,text:any,x:number,yTop:number,w:number,h:number,font:any,size=7,bold=false,align:'left'|'center'='left'){const f=font;const lines=wrap(clean(text),w-6,f,size).slice(0,Math.max(1,Math.floor((h-4)/(size+2))));lines.forEach((t,i)=>{let xx=x+3;if(align==='center')xx=x+(w-f.widthOfTextAtSize(t,size))/2;page.drawText(t,{x:xx,y:yTop-11-i*(size+2),size,font:f,color:rgb(.05,.08,.12)})});line(page,x,yTop,x+w,yTop);line(page,x,yTop-h,x+w,yTop-h);line(page,x,yTop,x,yTop-h);line(page,x+w,yTop,x+w,yTop-h)}
async function contextFor(reviewId:number,studentId:number){return (await query<any>(`SELECT ev.id evaluation_id,ev.status,ev.verified_at,ev.hod_user_id,rv.id review_id,rv.name review_name,rv.subject_code,rv.maximum_marks,pc.semester,t.id team_id,t.team_code,t.team_name,p.title project_title,pr.name program_name,COALESCE(pr.department,'CSE') department,se.code section,f.name guide_name,f.designation guide_designation,f.department guide_department,hu.display_name hod_name FROM review_evaluations_v3 ev JOIN pbl_reviews_v2 rv ON rv.id=ev.review_id JOIN teams_v2 t ON t.id=ev.team_id JOIN pbl_cycles_v2 pc ON pc.id=t.pbl_cycle_id JOIN programs_v2 pr ON pr.id=pc.program_id JOIN team_members_v2 tm ON tm.team_id=t.id AND tm.status='ACTIVE' JOIN student_enrollments_v2 own_e ON own_e.id=tm.enrollment_id AND own_e.student_id=$2 JOIN sections_v2 se ON se.id=own_e.section_id LEFT JOIN project_allocations_v2 pa ON pa.team_id=t.id AND pa.status='ACTIVE' LEFT JOIN projects_v2 p ON p.id=pa.project_id LEFT JOIN faculty_v2 f ON f.id=ev.guide_faculty_id LEFT JOIN users_v2 hu ON hu.id=ev.hod_user_id WHERE ev.review_id=$1 AND ev.status='VERIFIED' LIMIT 1`,[reviewId,studentId]))[0]}
export async function GET(req:Request,{params}:{params:Promise<{reviewId:string}>}){const u=await requireAnyRole(['STUDENT']);if(!u?.studentId)return new NextResponse('Unauthorised',{status:401});const {reviewId}=await params;const rid=Number(reviewId);const ctx=await contextFor(rid,u.studentId);if(!ctx)return new NextResponse('Rubric sheet is available only after HoD verification.',{status:403});const scores=await query<any>(`SELECT ri.id,ri.co_code,ri.criterion_name,ri.max_marks,ri.display_order,trs.marks_awarded,trs.selected_level_id,COALESCE(jsonb_agg(jsonb_build_object('id',rl.id,'label',rl.level_label,'marks',rl.marks,'descriptor',rl.descriptor,'order',rl.display_order) ORDER BY rl.display_order) FILTER(WHERE rl.id IS NOT NULL),'[]'::jsonb) levels FROM team_rubric_scores_v3 trs JOIN rubric_items_v2 ri ON ri.id=trs.rubric_item_id LEFT JOIN rubric_levels_v2 rl ON rl.rubric_item_id=ri.id WHERE trs.evaluation_id=$1 GROUP BY ri.id,trs.marks_awarded,trs.selected_level_id ORDER BY ri.display_order`,[ctx.evaluation_id]);const students=await query<any>(`SELECT s.name,s.usn,sc.contribution_percent FROM student_contributions_v3 sc JOIN student_enrollments_v2 e ON e.id=sc.enrollment_id JOIN students_v2 s ON s.id=e.student_id WHERE sc.evaluation_id=$1 ORDER BY s.usn`,[ctx.evaluation_id]);const coMarks:Record<string,number>={},coMax:Record<string,number>={};scores.forEach((x:any)=>{const co=x.co_code||'CO';coMarks[co]=(coMarks[co]||0)+Number(x.marks_awarded);coMax[co]=(coMax[co]||0)+Number(x.max_marks)});const coCodes=Object.keys(coMarks);const teamTotal=Object.values(coMarks).reduce((a,b)=>a+b,0);const totalMax=Object.values(coMax).reduce((a,b)=>a+b,0);
 const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 // Page 1
 let page=pdf.addPage(A4);center(page,'GM UNIVERSITY',812,bold,15);center(page,'Faculty of Engineering and Technology',794,bold,10);center(page,`Department / Program: ${ctx.department} / ${ctx.program_name}`,779,regular,8.5);center(page,`PROJECT-BASED LEARNING (PBL) ASSESSMENT - ${ctx.review_name}`,760,bold,10.5);
 let y=740;drawText(page,`Semester: ${ctx.semester}     Section: ${ctx.section}     Subject Code: ${ctx.subject_code||'-'}`,40,y,bold,8.5);y-=17;drawText(page,`Team: ${ctx.team_code} - ${ctx.team_name}`,40,y,regular,8.5);y-=17;drawText(page,`Project Name: ${ctx.project_title||'-'}`,40,y,regular,8.5,515);y-=24;
 const x0=24;const widths=[30,100,28,68,68,68,68,68,45];const headers=['CO','Criteria','Max','Level 5','Level 4','Level 3','Level 2','Level 1','Obtained'];let xx=x0;headers.forEach((h,i)=>{cell(page,h,xx,y,widths[i],30,bold,6.4,false,'center');xx+=widths[i]});y-=30;
 for(const s of scores){const h=70;xx=x0;const levels=(s.levels||[]).slice(0,5);const vals=[s.co_code||'',s.criterion_name,Number(s.max_marks).toFixed(2),...Array.from({length:5},(_,i)=>{const l=levels[i];return l?`${Number(l.id)===Number(s.selected_level_id)?'[X] ':''}${l.label}: ${l.descriptor}`:''}),Number(s.marks_awarded).toFixed(2)];vals.forEach((v:any,i)=>{cell(page,v,xx,y,widths[i],h,i===8?bold:regular,6.1,false,i===0||i===2||i===8?'center':'left');xx+=widths[i]});y-=h;if(y<100)break;}
 y-=10;drawText(page,`Team Rubric Total: ${teamTotal.toFixed(2)} / ${totalMax.toFixed(2)}`,40,y,bold,9);y-=16;drawText(page,`Verification Status: VERIFIED    Verified on: ${ctx.verified_at?new Date(ctx.verified_at).toLocaleDateString('en-IN'):'-'}`,40,y,regular,8);
 // Page 2
 page=pdf.addPage(A4);center(page,'GM UNIVERSITY',812,bold,15);center(page,'Faculty of Engineering and Technology',794,bold,10);center(page,`PBL ${ctx.review_name} - STUDENT MARKS & OFFLINE SIGNATURE SHEET`,775,bold,10);y=750;drawText(page,`Project Name: ${ctx.project_title||'-'}`,32,y,bold,8.5,530);y-=18;drawText(page,`Team: ${ctx.team_code} - ${ctx.team_name}     Semester: ${ctx.semester}     Section: ${ctx.section}`,32,y,regular,8.5);y-=17;drawText(page,'Individual marks are system-derived from the verified team rubric marks x the Contribution Indicator.',32,y,regular,7.7,530);y-=25;
 const fixed=[110,82,60];const coW=Math.max(38,Math.min(55,(535-fixed.reduce((a,b)=>a+b,0)-70)/Math.max(1,coCodes.length)));const widths2=[110,82,60,...coCodes.map(()=>coW),55,70];const head2=['Student Name','USN','Contribution',...coCodes.map(c=>`${c} (${coMax[c].toFixed(0)})`),`Total (${totalMax.toFixed(0)})`,'Student Signature'];xx=30;head2.forEach((h,i)=>{cell(page,h,xx,y,widths2[i],32,bold,6.5,false,'center');xx+=widths2[i]});y-=32;
 for(const st of students){const pct=Number(st.contribution_percent);const vals=[st.name,st.usn,`${pct.toFixed(2).replace(/\.00$/,'')}%`,...coCodes.map(c=>(coMarks[c]*pct/100).toFixed(2)),(teamTotal*pct/100).toFixed(2),''];xx=30;vals.forEach((v:any,i)=>{cell(page,v,xx,y,widths2[i],36,i===vals.length-2?bold:regular,6.8,false,i>=2&&i<vals.length-1?'center':'left');xx+=widths2[i]});y-=36;}
 y-=20;drawText(page,'Project Guide',40,y,bold,9);drawText(page,'Head of Department',325,y,bold,9);y-=20;drawText(page,`Name: ${ctx.guide_name||'________________________'}`,40,y,regular,8.2);drawText(page,`Name: ${ctx.hod_name||'________________________'}`,325,y,regular,8.2);y-=24;drawText(page,'Signature: ______________________________',40,y,regular,8.2);drawText(page,'Signature: ______________________________',325,y,regular,8.2);y-=24;drawText(page,'Date: __________________',40,y,regular,8.2);drawText(page,'Date: __________________',325,y,regular,8.2);y-=35;drawText(page,'Physical submission procedure: Students sign in the table above, Project Guide signs, HoD signs, and the printed copy is submitted physically to the PBL Coordinator.',40,y,regular,7.8,510,10);const code=`PBL-${ctx.review_id}-${ctx.team_id}-${ctx.evaluation_id}`;drawText(page,`System Generated Verified PBL Review | Verification ID: ${code}`,120,38,regular,7.2);
 const bytes=await pdf.save();const c=await pool.connect();try{await c.query(`INSERT INTO rubric_pdf_access_log_v4(evaluation_id,downloaded_by_user_id,verification_code) VALUES($1,$2,$3)`,[ctx.evaluation_id,u.id,code])}finally{c.release()}return new NextResponse(Buffer.from(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${clean(ctx.team_code)}_${clean(ctx.review_name).replace(/\s+/g,'_')}_Verified_Rubric.pdf"`}})}
