'use client';
import { useState } from 'react';

type Level={label:string;marks:number;descriptor:string};
type Item={co:string;name:string;maxMarks:number;levels:Level[]};
type Req={type:string;title:string;description:string;required:boolean;maxSizeMB:number;extensions:string;maxFiles:number;instructions:string;urlKind:'ANY'|'YOUTUBE';customType:string};
const newItem=():Item=>({co:'CO1',name:'',maxMarks:5,levels:[5,4,3,2,1].map(n=>({label:`Level ${n}`,marks:n,descriptor:''}))});
const defaultExt=(t:string)=>({PDF:'pdf',PPT:'ppt,pptx',DOC:'doc,docx',ZIP:'zip',IMAGE:'png,jpg,jpeg',CSV:'csv',EXCEL:'xls,xlsx',SOURCE_CODE:'c,cpp,h,java,py,js,ts'} as Record<string,string>)[t]||'';
const newReq=():Req=>({type:'PDF',title:'Project Report',description:'',required:true,maxSizeMB:1,extensions:'pdf',maxFiles:1,instructions:'',urlKind:'ANY',customType:''});
function parseCSV(text:string):Item[]{const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const split=(s:string)=>{const out:string[]=[];let cur='',q=false;for(let i=0;i<s.length;i++){const ch=s[i];if(ch==='"'){if(q&&s[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out.map(x=>x.trim())};const h=split(lines[0]).map(x=>x.toLowerCase());const map=new Map<string,Item>();for(const line of lines.slice(1)){const a=split(line);const get=(n:string)=>a[h.indexOf(n)]||'';const name=get('criterion');if(!name)continue;const key=`${get('co')}|${name}`;if(!map.has(key))map.set(key,{co:get('co'),name,maxMarks:Number(get('max marks')||0),levels:[]});map.get(key)!.levels.push({label:get('level')||`Level ${get('level marks')}`,marks:Number(get('level marks')||0),descriptor:get('descriptor')})}return [...map.values()]}

export default function RubricDesigner({cycles}:{cycles:Array<{id:number;semester:number;name:string}>}){
 const [items,setItems]=useState<Item[]>([newItem()]);const [requirements,setRequirements]=useState<Req[]>([]);const [title,setTitle]=useState('PBL Assessment Rubric');const [reviewName,setReviewName]=useState('Review 1');const [cycle,setCycle]=useState(cycles[0]?.id||0);const total=items.reduce((s,i)=>s+Number(i.maxMarks||0),0);
 function patch(i:number,p:Partial<Item>){setItems(x=>x.map((v,k)=>k===i?{...v,...p}:v))}function patchLevel(i:number,j:number,p:Partial<Level>){setItems(x=>x.map((v,k)=>k===i?{...v,levels:v.levels.map((l,z)=>z===j?{...l,...p}:l)}:v))}function patchReq(i:number,p:Partial<Req>){setRequirements(x=>x.map((v,k)=>k===i?{...v,...p}:v))}async function importFile(file:File){const parsed=parseCSV(await file.text());if(parsed.length)setItems(parsed)}
 return <div className="form"><h1>Rubric & Review Designer</h1><p>Create the review, rubric and its team submission requirements together. Existing reviews without file requirements continue to work normally.</p><form action="/api/coordinator/rubrics" method="post"><input type="hidden" name="rubricJson" value={JSON.stringify({items})}/><input type="hidden" name="requirementsJson" value={JSON.stringify({requirements})}/>
 <h2>1. Review Information</h2><div className="field"><label>PBL Cycle</label><select name="pblCycleId" value={cycle} onChange={e=>setCycle(Number(e.target.value))}>{cycles.map(c=><option key={c.id} value={c.id}>{c.name} — Semester {c.semester}</option>)}</select></div><div className="field"><label>Review name / number</label><input name="reviewName" value={reviewName} onChange={e=>setReviewName(e.target.value)} required/></div><div className="field"><label>Subject code</label><input name="subjectCode"/></div>
 <h2>2. Rubric Details</h2><div className="field"><label>Rubric title</label><input name="title" value={title} onChange={e=>setTitle(e.target.value)} required/></div><div className="notice"><b>Total rubric marks: {total}</b></div>
 <h2>3. Rubric Criteria / COs</h2>{items.map((it,i)=><div className="card" key={i}><div className="designer-grid"><input value={it.co} onChange={e=>patch(i,{co:e.target.value})} placeholder="CO5"/><input value={it.name} onChange={e=>patch(i,{name:e.target.value})} placeholder="Criterion name" required/><input type="number" min="0" step="0.5" value={it.maxMarks} onChange={e=>patch(i,{maxMarks:Number(e.target.value)})}/></div><h3>Performance levels</h3>{it.levels.map((l,j)=><div key={j} className="level-grid"><input value={l.label} onChange={e=>patchLevel(i,j,{label:e.target.value})}/><input type="number" step="0.5" value={l.marks} onChange={e=>patchLevel(i,j,{marks:Number(e.target.value)})}/><input value={l.descriptor} onChange={e=>patchLevel(i,j,{descriptor:e.target.value})} placeholder="Performance descriptor"/><button type="button" className="btn secondary" onClick={()=>patch(i,{levels:it.levels.filter((_,z)=>z!==j)})}>Remove</button></div>)}<button type="button" className="btn secondary" onClick={()=>patch(i,{levels:[...it.levels,{label:`Level ${it.levels.length+1}`,marks:0,descriptor:''}]})}>+ Level</button> <button type="button" className="btn danger" onClick={()=>setItems(x=>x.filter((_,k)=>k!==i))}>Delete Criterion</button></div>)}<button type="button" className="btn secondary" onClick={()=>setItems(x=>[...x,newItem()])}>+ Criterion</button>
 <hr/><div className="field"><label>Import rubric CSV</label><input type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><small>Columns: Criterion, CO, Max Marks, Level, Level Marks, Descriptor.</small></div>
 <h2>4. Required Submission Files</h2><p className="muted">Team submission. Usually 1–2 files with a 1 MB default limit. Video files are not accepted; use a YouTube link requirement instead.</p>{requirements.map((r,i)=><div className="card" key={i}><h3>Requirement {i+1}</h3><div className="field"><label>File / link type</label><select value={r.type} onChange={e=>{const t=e.target.value;patchReq(i,{type:t,extensions:defaultExt(t)})}}><option>PDF</option><option>PPT</option><option>DOC</option><option>ZIP</option><option>IMAGE</option><option>CSV</option><option>EXCEL</option><option>URL</option><option>SOURCE_CODE</option><option>OTHER</option></select></div>{r.type==='OTHER'&&<div className="field"><label>Custom type</label><input value={r.customType} onChange={e=>patchReq(i,{customType:e.target.value})}/></div>}{r.type==='URL'&&<div className="field"><label>Link validation</label><select value={r.urlKind} onChange={e=>patchReq(i,{urlKind:e.target.value as 'ANY'|'YOUTUBE'})}><option value="ANY">Any HTTPS/HTTP link</option><option value="YOUTUBE">YouTube link only</option></select></div>}<div className="field"><label>Title</label><input value={r.title} onChange={e=>patchReq(i,{title:e.target.value})} required/></div><div className="field"><label>Description</label><textarea value={r.description} onChange={e=>patchReq(i,{description:e.target.value})}/></div><label className="rubric-choice"><input type="checkbox" checked={r.required} onChange={e=>patchReq(i,{required:e.target.checked})}/> Required</label>{r.type!=='URL'&&<><div className="field"><label>Maximum size per file (MB)</label><input type="number" min="0.1" max="1" step="0.1" value={r.maxSizeMB} onChange={e=>patchReq(i,{maxSizeMB:Number(e.target.value)})}/></div><div className="field"><label>Allowed extensions (comma separated, without dots)</label><input value={r.extensions} onChange={e=>patchReq(i,{extensions:e.target.value})} placeholder="pdf"/></div><div className="field"><label>Maximum number of files</label><input type="number" min="1" max="10" value={r.maxFiles} onChange={e=>patchReq(i,{maxFiles:Number(e.target.value)})}/></div></>}<div className="field"><label>Instructions</label><textarea value={r.instructions} onChange={e=>patchReq(i,{instructions:e.target.value})}/></div><button type="button" className="btn secondary" disabled={i===0} onClick={()=>setRequirements(x=>{const y=[...x];[y[i-1],y[i]]=[y[i],y[i-1]];return y})}>↑</button> <button type="button" className="btn secondary" disabled={i===requirements.length-1} onClick={()=>setRequirements(x=>{const y=[...x];[y[i+1],y[i]]=[y[i],y[i+1]];return y})}>↓</button> <button type="button" className="btn danger" onClick={()=>setRequirements(x=>x.filter((_,k)=>k!==i))}>Remove</button></div>)}<button type="button" className="btn secondary" onClick={()=>setRequirements(x=>[...x,newReq()])}>+ Add File Requirement</button>
 <h2>5. Dates</h2><div className="field"><label>Review date</label><input name="reviewDate" type="date"/></div><div className="field"><label>Submission start date/time</label><input name="submissionOpenAt" type="datetime-local"/></div><div className="field"><label>Submission deadline</label><input name="submissionDeadline" type="datetime-local"/></div>
 <button className="btn secondary" name="action" value="SAVE_DRAFT">Save Draft</button> <button className="btn" name="action" value="PUBLISH">Publish Review</button></form></div>
}
